<?php
declare(strict_types=1);

require_once __DIR__ . '/AgentProvider.php';

final class NullAgent implements AgentProvider
{
    public function decide(array $thread): string
    {
        // Simple heuristic: if status new => post, if posting => verify else skip
        $status = $thread['status'] ?? 'new';
        return match($status) {
            'new' => 'post',
            'queued' => 'post',
            'posting' => 'verify',
            default => 'skip'
        };
    }

    public function composeReply(array $thread, array $account): string
    {
        $title = $thread['title'] ?? '';
        $host = $thread['host'] ?? '';
        // TODO: integrate OpenAI later
        return trim("Привет! Спасибо за обсуждение темы: {$title}. Если нужны подробности — могу поделиться опытом. (autogenerated stub)");
    }
}
